name: SSH Connection Test

on:
  workflow_dispatch: # 手動実行可能
  push:
    branches:
      - debug-deploy

jobs:
  job1:
    name: SSH Test
    runs-on: ubuntu-latest

    steps:
      - name: SSH connection test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }} # 空なら空白でOK
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "SSH connection OK"
